apiVersion: client.authentication.k8s.io/v1beta1
kind: Deployment
metadata:
  name: nodechat-deployment
  labels:
    app: nodechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodechat
  template:
    metadata:
      labels:
        app: nodechat
    spec:
      containers:
      - name: nodechat
        image: niskarsha10/nodejsproject
        ports:
        - containerPort: 3000
